version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: webapilab-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Your_password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:
      - app-network
    volumes:
      - sql-data:/var/opt/mssql

  webapilab-api:
    build:
      context: .
      dockerfile: WebApiLabDevOps.Api/Dockerfile
    container_name: webapilab-api
    ports:
      - "5000:8080"
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=WeatherDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True;
    networks:
      - app-network

networks:
  app-network:

volumes:
  sql-data:
